universe = vanilla
executable = build_clustering.sh
log = clustering_data.log
output = clustering_data.out
error = clustering_data.err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = kaggle.json, http://proxy.chtc.wisc.edu/SQUID/chtc/el8/python37.tar.gz, analyze_data.py, analyze_data_2.py, analyze_data_3.py, analyze_data_clustering.py

# Resources
request_cpus = 1
request_memory = 5GB
request_disk = 50GB

queue
